### ISSUE TITLE
[Tasks]: Need a template title card for planned tutorial videos

### ISSUE THREAD

**Issue by rps102** [RISC-OS-Community/CodingOnRISC-OS#20]
### Background

A number of 'Getting started' tutorials are planned, which after the meeting will be made available on youtube (or similar video hosting) so that people can catch up later and also so they are indexed into search engines/referenced on wikis and so on.

A template for the videos is suggested, so they appear side by side to be part of a coherent series, rather than a jumble of styles put together by different authors. For example, the [ROUGOL talks](https://www.youtube.com/watch?v=jF5pIyQ0O-M&ab_channel=Leowhite) all follow a common style.

This doesn't need to be fancy or animated with sound and special effects, it could just be a static image
* Suggest 1920x1080 widescreen aspect
* Pick a common font like Arial which has clones on most platforms, define the size/position of the lines of title and subtitle text
* Define the transition from the title to the content (fade? cut? how many frames does the transition take?)

The alternative is for Paolo to "top & tail" all the videos prior to publishing rather than relying on individual contributors to get it right.

### Definition of Done

- [ ] Task is done when a title card style is defined

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pzaino** [comment]
@rps102 

> Suggest 1920x1080 widescreen aspect

Sounds perfect, it's already the default used aspect for previous videos we made.

> Pick a common font like Arial which has clones on most platforms, define the size/position of the lines of title and subtitle text

Totally agree. 

For each subsection (for instance if a video is composed by multiple smaller chunks like Install tool X, first commit, push code) please leave some space so I can add a transition with subsection title.

All one has to do is either wait around 5 seconds after finished the previous subsection OR (better) just record each single subsection as a separate video (I'll glue them together in Final Cut Pro) and add subsection titles and transitions (again as we did already for previous videos). The advantage of this approach for the person who record a video is that they need to follow a shorter script and it's easier to get it right than doing a longer video take.

Up to you guys.

> Define the transition from the title to the content (fade? cut? how many frames does the transition take?)

I already have professionally made transitions/cuts etc., if you wish to inster them in your own video making this is fine, but some of them may be "software dependent), like .MOV or specific transition scripts for specific softwares. I use Final Cut Pro on macOS, so that probably imply you should use the same otherwise (again) I can add those and that will make everything absolutely same style.

Hope this helps and please others join this conversation with you ideas and suggestions.
- Paolo

**Comment by pzaino** [comment]
Also, here is a quick thought for a beginning of structure for each subsection videos:

```
1) How to install [your tool]
2) How to do its initial configuration
3) How to do a Git clone with [your tool]
4) How to do a Git add
5) How to do a Git commit
6) How to do a Git push
```

Do we want to demo more?
(for instance creating a branch and git pull etc?)

**Comment by gerph** [comment]
LOL. I'd not seen this, but it is basically the pattern that I've used.

Git on MacOS is about 12 minutes. I've got unscaled video at retina resolution, but that's far too unwieldy for any real use, so I've scaled down to 1728x1080, which is matching your requirements. I don't really see what I can cut out or be faster about to make it any shorter - I'll happily take suggestions though.

I've got a script for the video, which you can find here:

https://gist.github.com/gerph/896dd9f81a2d7b161f91174b00a34745

**Comment by rps102** [comment]
> > Pick a common font like Arial which has clones on most platforms, define the size/position of the lines of title
> > and subtitle text

[snip]

> All one has to do is either wait around 5 seconds after finished the previous subsection OR (better) just record each single subsection as a separate video (I'll glue them together in Final Cut Pro) and add subsection titles and transitions (again as we did already for previous videos). The advantage of this approach for the person who record a video is that they need to follow a shorter script and it's easier to get it right than doing a longer video take.

Ah, I see I've misunderstood the proposal here slightly. I thought we were each individually editing our videos, hence needing to define a font/transition style etc so they all look like a consistent series.

If, as I think I've understood, you're going to "top & tail" them all in Final Cut from raw footage we each provide, then it doesn't matter so much - you'll be self consistent with yourself!

Nothing too cheesy mind, we don't want star wipes like an 80's pop video...

**Comment by gerph** [comment]
I hope that mine, as a complete run through, isn't too bad. I'm not at all good at editing, so I've always tried to make a proper job in one long take... Plus my 'editing' consists of using ffmpeg command line tool - I don't really know how to edit things myself and don't have an editing app.

If anyone wants to see what I've done they're here: https://share.gerph.org/s/NyixBY7on6nq7KX - if there's anything wrong with them, please let me know. I can re-do them if needed but I would certainly take the hint to split into chunks of that were the case.

**Comment by pzaino** [comment]
@rps102 

> Nothing too cheesy mind, we don't want star wipes like an 80's pop video...

Damn, I though you would love some 80's pop video kinda thingy! 🤣 - Nevermind then, I'll use those for the ASM course! 😄 

> If, as I think I've understood, you're going to "top & tail" them all in Final Cut from raw footage we each provide, then it doesn't matter so much - you'll be self consistent with yourself!

Yes I am already working on @gerph and @ccawley2011 material, so at this point I am editing, if you still would like to edit yours I can share what I am doing, totally happy with that, otherwise I can edit yours as well, don't forget I'll need to balance the audio volume anyway so they all have same volume.

**Comment by pzaino** [comment]
@gerph ,

>  I'd not seen this, but it is basically the pattern that I've used.

Don't worry, and yes you did a great job, your videos are awesome! Thank you very much. Sorry for the late reply, but I had a busy day at work.

> Git on MacOS is about 12 minutes.

12 minutes is ok, don't worry. In general I recommend videos that are not shorter than 5 minutes and not longer than 15 minutes, so the avergae comes as 10 minutes, but all the "in-between" lenghts are fine. Generally people can't watch more than 15 minutes, so yeah that one is the hard limit.

> I've got a script for the video, which you can find here:

Thanks a lot, I am also preparing the subtitles for hearing imparied folks, I have an AI I use for that, but having your script makes things easier, so thank you very much! :)

**Comment by pzaino** [comment]
@gerph ,

> If anyone wants to see what I've done they're here

I played both your two videos and they both look great, thanks a lot. :)

**Comment by pzaino** [comment]
@rps102 ,
quick intro test, can you please check it to see if it's too cheesy for your tastes? :) 

https://riscoscommunity.org/mov/CodingOnROIntroTest.mov

Also after that intro there is a static frame with the presentation author name and the title of the presentation, so for instance  "Presenter Charles Ferguson - Using Git and Pyromaniac" kind of thing.

also @gerph and @ccawley2011 if you have feedback on the intro please let me know, thanks 😄 

Thanks,
- Paolo

P.S. to avoid future bandwidth issue the link above will be available for a limited time, JFYI :)

**Comment by gerph** [comment]
Looks ok to me, although that .mov doesn't play directly on FF or Chrome.

The wipes are a bit harsh to my eyes, but I'm not the best person to comment on how to present things :-)

**Comment by rps102** [comment]
> @rps102 , quick intro test, can you please check it to see if it's too cheesy for your tastes? :)
> 
> https://riscoscommunity.org/mov/CodingOnROIntroTest.mov

That looks good to me - animated, consistent use of fonts, not too much toasted cheese!

**Comment by pzaino** [comment]
@gerph ,
thanks for your feedback! :) 

> The wipes are a bit harsh to my eyes,

Modern style and obviously I am more into music videos and music bands interviews making, so obviously I need to improve on the "less presence" of tech videos I guess, sorry. 

> although that .mov doesn't play directly on FF or Chrome.

Sorry about that, trying to finish the work, so forgot to make it a bit more standard!

**Comment by pzaino** [comment]
@rps102 ,

thanks for your feedback man! :)

> That looks good to me - animated, consistent use of fonts, not too much toasted cheese!

Cool, I mean it's almost a mix between hi tech and a "Metallica" kinda style lol so shouldn't be too cheese! But now I wonder what kind of stuff you watch normaly 🤣

**Comment by pzaino** [comment]
@gerph ,
just a quick one, I fixed the playing in the browser now (might be useful in the future), so thanks for noticing it! :)
